CREATE TABLE `Factions` (
  `Name` text CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL,
  `Player` text CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL,
  `id` int NOT NULL AUTO_INCREMENT,
  `GameId` int NOT NULL,
  `Notes` text CHARACTER SET latin1 COLLATE latin1_general_ci,
  `GM_Notes` text CHARACTER SET latin1 COLLATE latin1_general_ci,
  `Features` text CHARACTER SET latin1 COLLATE latin1_general_ci,
  `MapColour` text CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL,
  `AccessKey` text CHARACTER SET latin1 COLLATE latin1_general_ci,
  `LastActive` int DEFAULT NULL,
  `Biosphere` int NOT NULL DEFAULT '0',
  `Biosphere2` int NOT NULL DEFAULT '0',
  `Biosphere3` int NOT NULL DEFAULT '0',
  `Trait1` text CHARACTER SET latin1 COLLATE latin1_general_ci,
  `Trait2` text CHARACTER SET latin1 COLLATE latin1_general_ci,
  `Trait3` text CHARACTER SET latin1 COLLATE latin1_general_ci,
  `Trait1Text` text CHARACTER SET latin1 COLLATE latin1_general_ci,
  `Trait2Text` text CHARACTER SET latin1 COLLATE latin1_general_ci,
  `Trait3Text` text CHARACTER SET latin1 COLLATE latin1_general_ci,
  `Credits` int NOT NULL DEFAULT '0',
  `PhysicsSP` int NOT NULL DEFAULT '0',
  `EngineeringSP` int NOT NULL DEFAULT '0',
  `XenologySP` int NOT NULL DEFAULT '0',
  `TurnState` int NOT NULL DEFAULT '0',
  `NPC` int NOT NULL,
  `Image` text CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL,
  `Horizon` int NOT NULL,
  `Trait1Automated` int NOT NULL,
  `Trait2Automated` int NOT NULL,
  `Trait3Automated` int NOT NULL,
  `Adjective` text CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL,
  `HomeWorld` int NOT NULL,
  `Currency1` int NOT NULL,
  `Currency2` int NOT NULL,
  `Currency3` int NOT NULL,
  `MapText` text CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL,
  `ThingType` int NOT NULL,
  `ThingBuild` int NOT NULL,
  `GMThingType` int NOT NULL,
  `GMThingBuild` int NOT NULL,
  `HasPrisoners` int NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;
