CREATE TABLE `GMLog4Later` (
  `id` int NOT NULL AUTO_INCREMENT,
  `What` text CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_bin;
