CREATE TABLE `Moons` (
  `id` int NOT NULL AUTO_INCREMENT,
  `PlanetId` int NOT NULL,
  `Name` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `ShortName` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `Radius` double NOT NULL,
  `Gravity` double NOT NULL,
  `Period` double NOT NULL,
  `OrbitalRadius` double NOT NULL,
  `Type` int NOT NULL DEFAULT '0',
  `Control` int NOT NULL DEFAULT '0',
  `Minerals` int NOT NULL DEFAULT '0',
  `Description` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `Image` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `ProjHome` int NOT NULL DEFAULT '0',
  `Attributes` int NOT NULL,
  `Mined` int NOT NULL,
  `GameId` int NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
