CREATE TABLE `Systems` (
  `GameId` int NOT NULL,
  `Ref` text CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL,
  `GridX` int DEFAULT NULL,
  `GridY` int DEFAULT NULL,
  `Notes` text CHARACTER SET latin1 COLLATE latin1_general_ci,
  `id` int NOT NULL AUTO_INCREMENT,
  `Control` int DEFAULT NULL,
  `HistoricalControl` int NOT NULL DEFAULT '0',
  `Name` text CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL,
  `ShortName` text CHARACTER SET latin1 COLLATE latin1_general_ci,
  `Nebulae` int DEFAULT NULL,
  `Description` text CHARACTER SET latin1 COLLATE latin1_general_ci,
  `Type` text CHARACTER SET latin1 COLLATE latin1_general_ci,
  `Radius` double DEFAULT NULL,
  `Mass` double DEFAULT NULL,
  `Temperature` double DEFAULT NULL,
  `Luminosity` double DEFAULT NULL,
  `Image` text CHARACTER SET latin1 COLLATE latin1_general_ci,
  `Image2` text CHARACTER SET latin1 COLLATE latin1_general_ci,
  `Type2` text CHARACTER SET latin1 COLLATE latin1_general_ci,
  `Radius2` double DEFAULT NULL,
  `Mass2` double DEFAULT NULL,
  `Temperature2` double DEFAULT NULL,
  `Luminosity2` double DEFAULT NULL,
  `Distance` double DEFAULT NULL,
  `Period` double DEFAULT NULL,
  `Category` int DEFAULT NULL,
  `StarName` text CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL,
  `StarName2` text CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL,
  `Flags` int NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;
