CREATE TABLE `Technologies` (
  `id` int NOT NULL AUTO_INCREMENT,
  `Cat` int NOT NULL,
  `Name` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `Field` int NOT NULL,
  `Description` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `PreReqTech` int DEFAULT NULL,
  `PreReqLevel` int DEFAULT NULL,
  `Slots` int DEFAULT NULL,
  `MinThingLevel` int DEFAULT NULL,
  `CivMil` int DEFAULT '0',
  `Formula` int DEFAULT '0',
  `DevState` int DEFAULT NULL,
  `Notes` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci,
  `PreReqTech2` int NOT NULL,
  `PreReqTech3` int NOT NULL,
  `Properties` int NOT NULL,
  `NotBy` int NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
