CREATE TABLE `Things` (
  `id` int NOT NULL AUTO_INCREMENT,
  `GameId` int NOT NULL,
  `Type` int NOT NULL DEFAULT '0',
  `SubType` int NOT NULL DEFAULT '0',
  `Level` int NOT NULL DEFAULT '1',
  `SystemId` int NOT NULL,
  `WithinSysLoc` int NOT NULL DEFAULT '1',
  `Name` text CHARACTER SET latin1 COLLATE latin1_bin,
  `Class` text CHARACTER SET latin1 COLLATE latin1_bin,
  `Whose` int NOT NULL DEFAULT '0',
  `Description` text CHARACTER SET latin1 COLLATE latin1_bin,
  `ProjectId` int NOT NULL DEFAULT '0',
  `CurHealth` int NOT NULL DEFAULT '1',
  `OrigHealth` int NOT NULL DEFAULT '1',
  `ShieldPoints` int NOT NULL,
  `CurShield` int NOT NULL,
  `Notes` text CHARACTER SET latin1 COLLATE latin1_bin,
  `GM_Notes` text CHARACTER SET latin1 COLLATE latin1_bin,
  `MaxDistricts` int NOT NULL DEFAULT '0',
  `MaxModules` int NOT NULL DEFAULT '0',
  `Image` text CHARACTER SET latin1 COLLATE latin1_bin,
  `Gadgets` text CHARACTER SET latin1 COLLATE latin1_bin,
  `BuildState` int NOT NULL DEFAULT '0',
  `NamedCrew` text CHARACTER SET latin1 COLLATE latin1_bin,
  `History` text CHARACTER SET latin1 COLLATE latin1_bin,
  `LinkId` int NOT NULL DEFAULT '0',
  `TargetKnown` int NOT NULL,
  `NewSystemId` int NOT NULL DEFAULT '0',
  `NewLocation` int NOT NULL DEFAULT '0',
  `ProjHome` int NOT NULL DEFAULT '0',
  `HasDeepSpace` int NOT NULL DEFAULT '0',
  `Orders` text CHARACTER SET latin1 COLLATE latin1_bin,
  `DesignValid` int NOT NULL DEFAULT '0',
  `Sensors` int NOT NULL,
  `SensorLevel` int NOT NULL,
  `NebSensors` int NOT NULL,
  `CargoSpace` int NOT NULL,
  `CargoUsed` int NOT NULL,
  `OtherFaction` int NOT NULL,
  `TurnBuilt` int NOT NULL,
  `Peaceful` int NOT NULL DEFAULT '1',
  `Speed` double NOT NULL DEFAULT '1',
  `Instruction` int NOT NULL,
  `Dist1` int NOT NULL,
  `Dist2` int NOT NULL,
  `ActionsNeeded` int NOT NULL,
  `Progress` int NOT NULL,
  `Spare1` int NOT NULL,
  `CurInst` int NOT NULL,
  `MakeName` text CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
  `InstCost` int NOT NULL,
  `LinkPay` int NOT NULL,
  `LinkCost` int NOT NULL,
  `SeenTypeMask` int NOT NULL,
  `PrisonerOf` int NOT NULL,
  `Priority` int NOT NULL,
  `LastMoved` int NOT NULL,
  `HiddenControl` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_bin;
